olympus:
  datasources:
    - url: jdbc:mysql://localhost:3306/liq_01?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456Ms3
    - url: jdbc:mysql://localhost:3306/liq_02?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456Ms3
    - url: jdbc:mysql://localhost:3306/liq_03?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456Ms3
