spring:
  h2:
    console:
      enabled: true
  datasource:
    druid:
      url: jdbc:h2:mem:client-whitelist;DB_CLOSE_DELAY=-1
      username: uaa
      password:
      test-while-idle: true
      validation-query: select 1
mybatis-plus:
  mapper-locations: classpath:com/cloudhelios/olympus/security/*/*Mapper.xml
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    sql-parser-cache: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
