olympus:
  list:
    - p1: test1
      p2: test1
    - p1: test2
      p2: test2
  map:
    p1:
      p1: test1
      p2: test1
    p2:
      p1: test2
      p2: test2
  dataSources:
    - url: jdbc:h2:mem:db01;DB_CLOSE_DELAY=-1
      username: test
  dataSourceMap:
    db01:
      url: jdbc:h2:mem:db01;DB_CLOSE_DELAY=-1
      username: test
    db02:
      url: jdbc:h2:mem:db02;DB_CLOSE_DELAY=-1
      username: test